name: CodeQL Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: typescript

      - name: Build CodeQL database
        uses: github/codeql-action/analyze@v1
        with:
          category: "CodeQL Analysis"
          
      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.codeql-analysis.outputs.sarif }}
          
